# Experiment 01 — Raw Dataset Inspection
Load `train_data.csv` and inspect the dataset without making any modifications.

In [80]:
import pandas as pd

df = pd.read_csv('train_data.csv')
print('Dataset loaded successfully.')

Dataset loaded successfully.

## 1. Shape

In [81]:
print(f'Rows: {df.shape[0]}  |  Columns: {df.shape[1]}')
print(df.shape)

Rows: 81477  |  Columns: 50
(81477, 50)

## 2. First 5 Rows

In [82]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,?,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,?,?,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,?,?,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,?,?,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,?,?,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,35754,82637451,Caucasian,Male,[50-60),?,2,1,2,3,?,?,31,6,16,0,0,0,414,411,250,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30

## 3. Column Names

In [83]:
for i, col in enumerate(df.columns):
    print(f'  {i}: {col}')

  0: encounter_id
  1: patient_nbr
  2: race
  3: gender
  4: age
  5: weight
  6: admission_type_id
  7: discharge_disposition_id
  8: admission_source_id
  9: time_in_hospital
  10: payer_code
  11: medical_specialty
  12: num_lab_procedures
  13: num_procedures
  14: num_medications
  15: number_outpatient
  16: number_emergency
  17: number_inpatient
  18: diag_1
  19: diag_2
  20: diag_3
  21: number_diagnoses
  22: max_glu_serum
  23: A1Cresult
  24: metformin
  25: repaglinide
  26: nateglinide
  27: chlorpropamide
  28: glimepiride
  29: acetohexamide
  30: glipizide
  31: glyburide
  32: tolbutamide
  33: pioglitazone
  34: rosiglitazone
  35: acarbose
  36: miglitol
  37: troglitazone
  38: tolazamide
  39: examide
  40: citoglipton
  41: insulin
  42: glyburide-metformin
  43: glipizide-metformin
  44: glimepiride-pioglitazone
  45: metformin-rosiglitazone
  46: metformin-pioglitazone
  47: change
  48: diabetesMed
  49: readmitted

## 4. Data Types and Missing Values

In [84]:
info_df = pd.DataFrame({
    'Dtype': df.dtypes,
    'Non-Null': df.notna().sum(),
    'Missing': df.isna().sum(),
    'Missing %': (df.isna().sum() / len(df) * 100).round(2)
})
print(info_df.to_string())

                           Dtype  Non-Null  Missing  Missing %
encounter_id               int64     81477        0       0.00
patient_nbr                int64     81477        0       0.00
race                      object     81477        0       0.00
gender                    object     81477        0       0.00
age                       object     81477        0       0.00
weight                    object     81477        0       0.00
admission_type_id          int64     81477        0       0.00
discharge_disposition_id   int64     81477        0       0.00
admission_source_id        int64     81477        0       0.00
time_in_hospital           int64     81477        0       0.00
payer_code                object     81477        0       0.00
medical_specialty         object     81477        0       0.00
num_lab_procedures         int64     81477        0       0.00
num_procedures             int64     81477        0       0.00
num_medications            int64     81477        0       0.00
number_outpatient          int64     81477        0       0.00
number_emergency           int64     81477        0       0.00
number_inpatient           int64     81477        0       0.00
diag_1                    object     81477        0       0.00
diag_2                    object     81477        0       0.00
diag_3                    object     81477        0       0.00
number_diagnoses           int64     81477        0       0.00
max_glu_serum             object      4307    77170      94.71
A1Cresult                 object     13620    67857      83.28
metformin                 object     81477        0       0.00
repaglinide               object     81477        0       0.00
nateglinide               object     81477        0       0.00
chlorpropamide            object     81477        0       0.00
glimepiride               object     81477        0       0.00
acetohexamide             object     81477        0       0.00
glipizide                 object     81477        0       0.00
glyburide                 object     81477        0       0.00
tolbutamide               object     81477        0       0.00
pioglitazone              object     81477        0       0.00
rosiglitazone             object     81477        0       0.00
acarbose                  object     81477        0       0.00
miglitol                  object     81477        0       0.00
troglitazone              object     81477        0       0.00
tolazamide                object     81477        0       0.00
examide                   object     81477        0       0.00
citoglipton               object     81477        0       0.00
insulin                   object     81477        0       0.00
glyburide-metformin       object     81477        0       0.00
glipizide-metformin       object     81477        0       0.00
glimepiride-pioglitazone  object     81477        0       0.00
metformin-rosiglitazone   object     81477        0       0.00
metformin-pioglitazone    object     81477        0       0.00
change                    object     81477        0       0.00
diabetesMed               object     81477        0       0.00
readmitted                object     81477        0       0.00

## 5. Value Counts — `readmitted`

In [85]:
print(df['readmitted'].value_counts())
print()
print(df['readmitted'].value_counts(normalize=True).map('{:.2%}'.format))

readmitted
NO     43759
>30    28530
<30     9188
Name: count, dtype: int64

readmitted
NO     53.71%
>30    35.02%
<30    11.28%
Name: proportion, dtype: object

## 6. Value Counts — `gender`

In [86]:
print(df['gender'].value_counts())
print()
print(df['gender'].value_counts(normalize=True).map('{:.2%}'.format))

gender
Female             43880
Male               37594
Unknown/Invalid        3
Name: count, dtype: int64

gender
Female             53.86%
Male               46.14%
Unknown/Invalid     0.00%
Name: proportion, dtype: object

## 7. Value Counts — `race`

In [87]:
print(df['race'].value_counts())
print()
print(df['race'].value_counts(normalize=True).map('{:.2%}'.format))

race
Caucasian          60773
AfricanAmerican    15516
?                   1797
Hispanic            1643
Other               1222
Asian                526
Name: count, dtype: int64

race
Caucasian          74.59%
AfricanAmerican    19.04%
?                   2.21%
Hispanic            2.02%
Other               1.50%
Asian               0.65%
Name: proportion, dtype: object

## 8. Value Counts — `age`

In [88]:
print(df['age'].value_counts().sort_index())
print()
print(df['age'].value_counts(normalize=True).sort_index().map('{:.2%}'.format))

age
[0-10)        133
[10-20)       570
[20-30)      1330
[30-40)      3013
[40-50)      7782
[50-60)     13847
[60-70)     17859
[70-80)     21006
[80-90)     13718
[90-100)     2219
Name: count, dtype: int64

age
[0-10)       0.16%
[10-20)      0.70%
[20-30)      1.63%
[30-40)      3.70%
[40-50)      9.55%
[50-60)     16.99%
[60-70)     21.92%
[70-80)     25.78%
[80-90)     16.84%
[90-100)     2.72%
Name: proportion, dtype: object

---
## 9. Feature Selection
Select the 18 features of interest + target column `readmitted`.

In [89]:
selected_features = [
    'number_inpatient',
    'time_in_hospital',
    'number_emergency',
    'number_outpatient',
    'num_medications',
    'num_lab_procedures',
    'diabetesMed',
    'insulin',
    'metformin',
    'admission_type_id',
    'discharge_disposition_id',
    'max_glu_serum',
    'A1Cresult',
    'race',
    'age',
    'diag_1',
    'diag_2',
    'gender',
]

target = 'readmitted'

df_selected = df[selected_features + [target]].copy()
print(f'Selected DataFrame shape: {df_selected.shape}')
df_selected.head()

Selected DataFrame shape: (81477, 19)

,number_inpatient,time_in_hospital,number_emergency,number_outpatient,num_medications,num_lab_procedures,diabetesMed,insulin,metformin,admission_type_id,discharge_disposition_id,max_glu_serum,A1Cresult,race,age,diag_1,diag_2,gender,readmitted
0,0,1,0,0,1,41,No,No,No,6,25,NaN,NaN,Caucasian,[0-10),250.83,?,Female,NO
1,0,3,0,0,18,59,Yes,Up,No,1,1,NaN,NaN,Caucasian,[10-20),276,250.01,Female,>30
2,1,2,0,2,13,11,Yes,No,No,1,1,NaN,NaN,AfricanAmerican,[20-30),648,250,Female,NO
3,0,2,0,0,16,44,Yes,Up,No,1,1,NaN,NaN,Caucasian,[30-40),8,250.43,Male,NO
4,0,3,0,0,16,31,Yes,Steady,No,2,1,NaN,NaN,Caucasian,[50-60),414,411,Male,>30

## 10. Numerical vs Categorical Features

In [90]:
numerical_features = [
    'number_inpatient',
    'time_in_hospital',
    'number_emergency',
    'number_outpatient',
    'num_medications',
    'num_lab_procedures',
    'admission_type_id',
    'discharge_disposition_id',
]

categorical_features = [
    'diabetesMed',
    'insulin',
    'metformin',
    'max_glu_serum',
    'A1Cresult',
    'race',
    'age',
    'diag_1',
    'diag_2',
    'gender',
]

print(f'Numerical features  ({len(numerical_features)}):')
for col in numerical_features:
    print(f'  - {col:30s}  dtype: {df_selected[col].dtype}')

print(f'\nCategorical features ({len(categorical_features)}):')
for col in categorical_features:
    print(f'  - {col:30s}  dtype: {df_selected[col].dtype}')

print(f'\nTarget: {target}  dtype: {df_selected[target].dtype}')

Numerical features  (8):
  - number_inpatient                dtype: int64
  - time_in_hospital                dtype: int64
  - number_emergency                dtype: int64
  - number_outpatient               dtype: int64
  - num_medications                 dtype: int64
  - num_lab_procedures              dtype: int64
  - admission_type_id               dtype: int64
  - discharge_disposition_id        dtype: int64

Categorical features (10):
  - diabetesMed                     dtype: object
  - insulin                         dtype: object
  - metformin                       dtype: object
  - max_glu_serum                   dtype: object
  - A1Cresult                       dtype: object
  - race                            dtype: object
  - age                             dtype: object
  - diag_1                          dtype: object
  - diag_2                          dtype: object
  - gender                          dtype: object

Target: readmitted  dtype: object

---
## 11. ICD-9 Diagnosis Code Mapping (`diag_1`, `diag_2`)

The raw `diag_1` and `diag_2` columns contain ~700 unique ICD-9 codes each.  
We map them into **9 broad clinical categories** so they can be encoded as categorical features.

| ICD-9 Range | Category |
|---|---|
| 390–459, 785 | Circulatory |
| 460–519, 786 | Respiratory |
| 520–579, 787 | Digestive |
| 250.xx | Diabetes |
| 800–999 | Injury |
| 710–739 | Musculoskeletal |
| 580–629, 788 | Genitourinary |
| 140–239 | Neoplasms |
| Everything else | Other |

In [91]:
def map_diagnosis(code):
    """Map a single ICD-9 code (string) to a clinical category."""
    if code == '?' or pd.isna(code):
        return 'Other'
    
    # Handle E and V codes
    if str(code).startswith('E') or str(code).startswith('V'):
        return 'Other'
    
    try:
        numeric = float(code)
    except ValueError:
        return 'Other'
    
    # Diabetes
    if 250 <= numeric < 251:
        return 'Diabetes'
    # Circulatory
    elif (390 <= numeric <= 459) or numeric == 785:
        return 'Circulatory'
    # Respiratory
    elif (460 <= numeric <= 519) or numeric == 786:
        return 'Respiratory'
    # Digestive
    elif (520 <= numeric <= 579) or numeric == 787:
        return 'Digestive'
    # Injury
    elif 800 <= numeric <= 999:
        return 'Injury'
    # Musculoskeletal
    elif 710 <= numeric <= 739:
        return 'Musculoskeletal'
    # Genitourinary
    elif (580 <= numeric <= 629) or numeric == 788:
        return 'Genitourinary'
    # Neoplasms
    elif 140 <= numeric <= 239:
        return 'Neoplasms'
    else:
        return 'Other'

print('Mapping function defined.')

Mapping function defined.

In [92]:
# Apply mapping to both diagnosis columns
df_selected['diag_1'] = df_selected['diag_1'].apply(map_diagnosis)
df_selected['diag_2'] = df_selected['diag_2'].apply(map_diagnosis)

print('Mapping applied successfully.\n')

print('=== diag_1 (mapped) ===')
print(df_selected['diag_1'].value_counts())
print()

print('=== diag_2 (mapped) ===')
print(df_selected['diag_2'].value_counts())

Mapping applied successfully.

=== diag_1 (mapped) ===
diag_1
Circulatory        24391
Other              14469
Respiratory        11511
Digestive           7643
Diabetes            7053
Injury              5626
Genitourinary       4129
Musculoskeletal     3941
Neoplasms           2714
Name: count, dtype: int64

=== diag_2 (mapped) ===
diag_2
Circulatory        25592
Other              21591
Diabetes           10158
Respiratory         8745
Genitourinary       6676
Digestive           3334
Neoplasms           2006
Injury              1936
Musculoskeletal     1439
Name: count, dtype: int64

In [93]:
# Verify: confirm both columns now have a small set of clean categories
print(f'diag_1 unique categories: {df_selected["diag_1"].nunique()}  ->  {sorted(df_selected["diag_1"].unique())}')
print(f'diag_2 unique categories: {df_selected["diag_2"].nunique()}  ->  {sorted(df_selected["diag_2"].unique())}')

diag_1 unique categories: 9  ->  ['Circulatory', 'Diabetes', 'Digestive', 'Genitourinary', 'Injury', 'Musculoskeletal', 'Neoplasms', 'Other', 'Respiratory']
diag_2 unique categories: 9  ->  ['Circulatory', 'Diabetes', 'Digestive', 'Genitourinary', 'Injury', 'Musculoskeletal', 'Neoplasms', 'Other', 'Respiratory']

---
## 12. Encode Categorical Features

**Encoding strategy:**

| Encoding | Features | Reason |
|---|---|---|
| **Label (binary)** | `diabetesMed`, `gender` | Binary Yes/No or Male/Female |
| **Label (ordinal)** | `insulin`, `metformin`, `max_glu_serum`, `A1Cresult`, `age` | Natural order exists |
| **One-Hot** | `race`, `diag_1`, `diag_2` | Nominal — no natural order |
| **Binary (target)** | `readmitted` | 0 = NO or >30 days, 1 = <30 days |

In [94]:
# ---- 12a. Binary Encoding ----

# diabetesMed: No=0, Yes=1
df_selected['diabetesMed'] = df_selected['diabetesMed'].map({'No': 0, 'Yes': 1})

# gender: Female=0, Male=1  (drop 3 Unknown/Invalid rows)
df_selected = df_selected[df_selected['gender'] != 'Unknown/Invalid']
df_selected['gender'] = df_selected['gender'].map({'Female': 0, 'Male': 1})

print('Binary encoding applied:')
print(f"  diabetesMed -> {sorted(df_selected['diabetesMed'].unique())}")
print(f"  gender      -> {sorted(df_selected['gender'].unique())}")
print(f'  Rows after dropping Unknown/Invalid gender: {len(df_selected)}')

Binary encoding applied:
  diabetesMed -> [np.int64(0), np.int64(1)]
  gender      -> [np.int64(0), np.int64(1)]
  Rows after dropping Unknown/Invalid gender: 81474

In [95]:
# ---- 12b. Ordinal Encoding ----

# insulin: No=0, Down=1, Steady=2, Up=3
insulin_map = {'No': 0, 'Down': 1, 'Steady': 2, 'Up': 3}
df_selected['insulin'] = df_selected['insulin'].map(insulin_map)

# metformin: No=0, Down=1, Steady=2, Up=3
metformin_map = {'No': 0, 'Down': 1, 'Steady': 2, 'Up': 3}
df_selected['metformin'] = df_selected['metformin'].map(metformin_map)

# max_glu_serum: NaN=0 (None/not measured), Norm=1, >200=2, >300=3
glu_map = {'Norm': 1, '>200': 2, '>300': 3}
df_selected['max_glu_serum'] = df_selected['max_glu_serum'].map(glu_map).fillna(0).astype(int)

# A1Cresult: NaN=0 (not measured), Norm=1, >7=2, >8=3
a1c_map = {'Norm': 1, '>7': 2, '>8': 3}
df_selected['A1Cresult'] = df_selected['A1Cresult'].map(a1c_map).fillna(0).astype(int)

# age: ordinal bins  [0-10)=0 ... [90-100)=9
age_map = {
    '[0-10)': 0, '[10-20)': 1, '[20-30)': 2, '[30-40)': 3, '[40-50)': 4,
    '[50-60)': 5, '[60-70)': 6, '[70-80)': 7, '[80-90)': 8, '[90-100)': 9
}
df_selected['age'] = df_selected['age'].map(age_map)

print('Ordinal encoding applied:')
for col, m in [('insulin', insulin_map), ('metformin', metformin_map),
               ('max_glu_serum', glu_map), ('A1Cresult', a1c_map), ('age', age_map)]:
    print(f'  {col:20s} -> {sorted(df_selected[col].unique())}')

Ordinal encoding applied:
  insulin              -> [np.int64(0), np.int64(1), np.int64(2), np.int64(3)]
  metformin            -> [np.int64(0), np.int64(1), np.int64(2), np.int64(3)]
  max_glu_serum        -> [np.int64(0), np.int64(1), np.int64(2), np.int64(3)]
  A1Cresult            -> [np.int64(0), np.int64(1), np.int64(2), np.int64(3)]
  age                  -> [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)]

In [96]:
# ---- 12c. One-Hot Encoding (nominal features) ----
# This REPLACES the original race, diag_1, diag_2 columns with dummy columns.
# The old columns are automatically dropped by pd.get_dummies.

nominal_features = ['race', 'diag_1', 'diag_2']

print(f'Shape BEFORE one-hot encoding: {df_selected.shape}')

df_selected = pd.get_dummies(df_selected, columns=nominal_features, drop_first=False)

# Convert bool columns to int (0/1) for consistency
bool_cols = df_selected.select_dtypes(include='bool').columns
df_selected[bool_cols] = df_selected[bool_cols].astype(int)

# Drop 'race_?' column — unknown/missing race is not a useful feature
df_selected.drop(columns=['race_?'], inplace=True)
print('Dropped column: race_?')

print(f'Shape AFTER  one-hot encoding: {df_selected.shape}')
print(f'\nNew one-hot columns:')
ohe_cols = [c for c in df_selected.columns if any(c.startswith(f'{nf}_') for nf in nominal_features)]
for col in sorted(ohe_cols):
    print(f'  - {col}')

Shape BEFORE one-hot encoding: (81474, 19)
Dropped column: race_?
Shape AFTER  one-hot encoding: (81474, 39)

New one-hot columns:
  - diag_1_Circulatory
  - diag_1_Diabetes
  - diag_1_Digestive
  - diag_1_Genitourinary
  - diag_1_Injury
  - diag_1_Musculoskeletal
  - diag_1_Neoplasms
  - diag_1_Other
  - diag_1_Respiratory
  - diag_2_Circulatory
  - diag_2_Diabetes
  - diag_2_Digestive
  - diag_2_Genitourinary
  - diag_2_Injury
  - diag_2_Musculoskeletal
  - diag_2_Neoplasms
  - diag_2_Other
  - diag_2_Respiratory
  - race_AfricanAmerican
  - race_Asian
  - race_Caucasian
  - race_Hispanic
  - race_Other

In [97]:
# ---- 12d. Target Encoding (Binary) ----
# 0 = NO readmission or readmitted AFTER 30 days  (NO, >30)
# 1 = Readmitted WITHIN 30 days                   (<30)

target_map = {'NO': 0, '>30': 0, '<30': 1}
df_selected['readmitted'] = df_selected['readmitted'].map(target_map)

print('Binary target encoding applied:')
print(f'  NO  -> 0')
print(f'  >30 -> 0')
print(f'  <30 -> 1')
print()
print(df_selected['readmitted'].value_counts().sort_index())
print()
print(df_selected['readmitted'].value_counts(normalize=True).sort_index().map('{:.2%}'.format))

Binary target encoding applied:
  NO  -> 0
  >30 -> 0
  <30 -> 1

readmitted
0    72286
1     9188
Name: count, dtype: int64

readmitted
0    88.72%
1    11.28%
Name: proportion, dtype: object

---
## 13. Final Encoded Dataset

Display the fully encoded dataset — all features are now numeric, ready for modelling.

In [98]:
print(f'Final shape: {df_selected.shape}')
print(f'All dtypes numeric: {df_selected.select_dtypes(include="object").columns.tolist() == []}')
print(f'NaN count: {df_selected.isna().sum().sum()}')
print()

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
df_selected.head(10)

Final shape: (81474, 39)
All dtypes numeric: True
NaN count: 0

,number_inpatient,time_in_hospital,number_emergency,number_outpatient,num_medications,num_lab_procedures,diabetesMed,insulin,metformin,admission_type_id,discharge_disposition_id,max_glu_serum,A1Cresult,age,gender,readmitted,race_AfricanAmerican,race_Asian,race_Caucasian,race_Hispanic,race_Other,diag_1_Circulatory,diag_1_Diabetes,diag_1_Digestive,diag_1_Genitourinary,diag_1_Injury,diag_1_Musculoskeletal,diag_1_Neoplasms,diag_1_Other,diag_1_Respiratory,diag_2_Circulatory,diag_2_Diabetes,diag_2_Digestive,diag_2_Genitourinary,diag_2_Injury,diag_2_Musculoskeletal,diag_2_Neoplasms,diag_2_Other,diag_2_Respiratory
0,0,1,0,0,1,41,0,0,0,6,25,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,0,3,0,0,18,59,1,3,0,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0
2,1,2,0,2,13,11,1,0,0,1,1,0,0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0
3,0,2,0,0,16,44,1,3,0,1,1,0,0,3,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0
4,0,3,0,0,16,31,1,2,0,2,1,0,0,5,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
5,0,5,0,0,12,73,1,0,0,1,1,0,0,7,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
6,0,13,0,0,28,68,1,2,0,2,1,0,0,8,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
7,0,12,0,0,18,33,1,2,0,3,3,0,0,9,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
8,0,9,0,0,17,47,1,2,0,1,1,0,0,4,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
9,0,7,0,0,11,62,1,2,0,2,1,0,0,6,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0

In [99]:
# Print all 39 feature columns + their dtypes
print(f'  {"#":>3s}  {"Column":38s}  {"Dtype":8s}  {"Unique":>6s}  Encoding')
print(f'  {"---":>3s}  {"":-<38s}  {"":-<8s}  {"":-<6s}  --------')

for i, col in enumerate(df_selected.columns):
    dtype = str(df_selected[col].dtype)
    uniq = df_selected[col].nunique()
    if col in ['number_inpatient','time_in_hospital','number_emergency',
               'number_outpatient','num_medications','num_lab_procedures',
               'admission_type_id','discharge_disposition_id']:
        enc = 'Numerical'
    elif col in ['diabetesMed','gender']:
        enc = 'Binary'
    elif col in ['insulin','metformin','max_glu_serum','A1Cresult','age']:
        enc = 'Ordinal'
    elif col == 'readmitted':
        enc = 'Target (binary)'
    else:
        enc = 'One-Hot'
    print(f'  {i:3d}  {col:38s}  {dtype:8s}  {uniq:6d}  {enc}')

print(f'\n  Total: {df_selected.shape[1]} columns  |  {df_selected.shape[0]} rows')

    #  Column                                  Dtype     Unique  Encoding
  ---  --------------------------------------  --------  ------  --------
    0  number_inpatient                        int64         17  Numerical
    1  time_in_hospital                        int64         14  Numerical
    2  number_emergency                        int64         31  Numerical
    3  number_outpatient                       int64         38  Numerical
    4  num_medications                         int64         74  Numerical
    5  num_lab_procedures                      int64        118  Numerical
    6  diabetesMed                             int64          2  Binary
    7  insulin                                 int64          4  Ordinal
    8  metformin                               int64          4  Ordinal
    9  admission_type_id                       int64          8  Numerical
   10  discharge_disposition_id                int64         26  Numerical
   11  max_glu_serum                           int64          4  Ordinal
   12  A1Cresult                               int64          4  Ordinal
   13  age                                     int64         10  Ordinal
   14  gender                                  int64          2  Binary
   15  readmitted                              int64          2  Target (binary)
   16  race_AfricanAmerican                    int64          2  One-Hot
   17  race_Asian                              int64          2  One-Hot
   18  race_Caucasian                          int64          2  One-Hot
   19  race_Hispanic                           int64          2  One-Hot
   20  race_Other                              int64          2  One-Hot
   21  diag_1_Circulatory                      int64          2  One-Hot
   22  diag_1_Diabetes                         int64          2  One-Hot
   23  diag_1_Digestive                        int64          2  One-Hot
   24  diag_1_Genitourinary                    int64          2  One-Hot
   25  diag_1_Injury                           int64          2  One-Hot
   26  diag_1_Musculoskeletal                  int64          2  One-Hot
   27  diag_1_Neoplasms                        int64          2  One-Hot
   28  diag_1_Other                            int64          2  One-Hot
   29  diag_1_Respiratory                      int64          2  One-Hot
   30  diag_2_Circulatory                      int64          2  One-Hot
   31  diag_2_Diabetes                         int64          2  One-Hot
   32  diag_2_Digestive                        int64          2  One-Hot
   33  diag_2_Genitourinary                    int64          2  One-Hot
   34  diag_2_Injury                           int64          2  One-Hot
   35  diag_2_Musculoskeletal                  int64          2  One-Hot
   36  diag_2_Neoplasms                        int64          2  One-Hot
   37  diag_2_Other                            int64          2  One-Hot
   38  diag_2_Respiratory                      int64          2  One-Hot

  Total: 39 columns  |  81474 rows

## 14. Encoded Demographics Summary

Display the final numbers for **age**, **gender**, and **race** after encoding.

In [100]:
print('=== AGE (Ordinal) ===')
age_labels = {0:'[0-10)',1:'[10-20)',2:'[20-30)',3:'[30-40)',4:'[40-50)',5:'[50-60)',6:'[60-70)',7:'[70-80)',8:'[80-90)',9:'[90-100)'}
age_counts = df_selected['age'].value_counts().sort_index()
for val, count in age_counts.items():
    print(f"  {val}  ({age_labels[val]}): {count}")
print()
print('=== GENDER (Binary) ===')
print('0 = Female  |  1 = Male')
print(df_selected['gender'].value_counts().sort_index())
print()
print('=== RACE (One-Hot) ===')
race_cols = [c for c in df_selected.columns if c.startswith('race_')]
for col in sorted(race_cols):
    print(f"  {col:25s}: {df_selected[col].sum()}")

=== AGE (Ordinal) ===
  0  ([0-10)): 133
  1  ([10-20)): 570
  2  ([20-30)): 1330
  3  ([30-40)): 3013
  4  ([40-50)): 7782
  5  ([50-60)): 13847
  6  ([60-70)): 17858
  7  ([70-80)): 21004
  8  ([80-90)): 13718
  9  ([90-100)): 2219

=== GENDER (Binary) ===
0 = Female  |  1 = Male
gender
0    43880
1    37594
Name: count, dtype: int64

=== RACE (One-Hot) ===
  race_AfricanAmerican     : 15516
  race_Asian               : 526
  race_Caucasian           : 60773
  race_Hispanic            : 1643
  race_Other               : 1221

---
# Test Dataset Processing

Apply the same feature engineering and encoding steps to the test dataset (`test_data.csv`). All variables are kept separate from the training set to avoid mixing data.

In [101]:
# Load test dataset
import pandas as pd
df_test = pd.read_csv('test_data.csv')
print('Test dataset loaded successfully.')

Test dataset loaded successfully.

In [102]:
# Select the same features as training
selected_features = [
    'number_inpatient', 'time_in_hospital', 'number_emergency', 'number_outpatient', 'num_medications', 'num_lab_procedures',
    'diabetesMed', 'insulin', 'metformin', 'admission_type_id', 'discharge_disposition_id', 'max_glu_serum', 'A1Cresult',
    'race', 'age', 'diag_1', 'diag_2', 'gender'
]
target = 'readmitted'
df_test_selected = df_test[selected_features + [target]].copy()
print(f'Selected test DataFrame shape: {df_test_selected.shape}')

Selected test DataFrame shape: (20289, 19)

In [103]:
# Map diagnosis codes
def map_diagnosis(code):
    if code == '?' or pd.isna(code):
        return 'Other'
    if str(code).startswith('E') or str(code).startswith('V'):
        return 'Other'
    try:
        numeric = float(code)
    except ValueError:
        return 'Other'
    if 250 <= numeric < 251:
        return 'Diabetes'
    elif (390 <= numeric <= 459) or numeric == 785:
        return 'Circulatory'
    elif (460 <= numeric <= 519) or numeric == 786:
        return 'Respiratory'
    elif (520 <= numeric <= 579) or numeric == 787:
        return 'Digestive'
    elif 800 <= numeric <= 999:
        return 'Injury'
    elif 710 <= numeric <= 739:
        return 'Musculoskeletal'
    elif (580 <= numeric <= 629) or numeric == 788:
        return 'Genitourinary'
    elif 140 <= numeric <= 239:
        return 'Neoplasms'
    else:
        return 'Other'
df_test_selected['diag_1'] = df_test_selected['diag_1'].apply(map_diagnosis)
df_test_selected['diag_2'] = df_test_selected['diag_2'].apply(map_diagnosis)

In [104]:
# Binary encoding
df_test_selected['diabetesMed'] = df_test_selected['diabetesMed'].map({'No': 0, 'Yes': 1})
df_test_selected = df_test_selected[df_test_selected['gender'] != 'Unknown/Invalid']
df_test_selected['gender'] = df_test_selected['gender'].map({'Female': 0, 'Male': 1})

In [105]:
# Ordinal encoding
insulin_map = {'No': 0, 'Down': 1, 'Steady': 2, 'Up': 3}
df_test_selected['insulin'] = df_test_selected['insulin'].map(insulin_map)
metformin_map = {'No': 0, 'Down': 1, 'Steady': 2, 'Up': 3}
df_test_selected['metformin'] = df_test_selected['metformin'].map(metformin_map)
glu_map = {'Norm': 1, '>200': 2, '>300': 3}
df_test_selected['max_glu_serum'] = df_test_selected['max_glu_serum'].map(glu_map).fillna(0).astype(int)
a1c_map = {'Norm': 1, '>7': 2, '>8': 3}
df_test_selected['A1Cresult'] = df_test_selected['A1Cresult'].map(a1c_map).fillna(0).astype(int)
age_map = {'[0-10)': 0, '[10-20)': 1, '[20-30)': 2, '[30-40)': 3, '[40-50)': 4, '[50-60)': 5, '[60-70)': 6, '[70-80)': 7, '[80-90)': 8, '[90-100)': 9}
df_test_selected['age'] = df_test_selected['age'].map(age_map)

In [106]:
# One-hot encoding
nominal_features = ['race', 'diag_1', 'diag_2']
df_test_selected = pd.get_dummies(df_test_selected, columns=nominal_features, drop_first=False)
bool_cols = df_test_selected.select_dtypes(include='bool').columns
df_test_selected[bool_cols] = df_test_selected[bool_cols].astype(int)
if 'race_?' in df_test_selected.columns:
    df_test_selected.drop(columns=['race_?'], inplace=True)

In [107]:
# Target encoding
target_map = {'NO': 0, '>30': 0, '<30': 1}
df_test_selected['readmitted'] = df_test_selected['readmitted'].map(target_map)

In [109]:
# Final check
print(f'Final test shape: {df_test_selected.shape}')
print(f'All dtypes numeric: {df_test_selected.select_dtypes(include="object").columns.tolist() == []}')
print(f'NaN count: {df_test_selected.isna().sum().sum()}')
df_test_selected.head()

Final test shape: (20289, 39)
All dtypes numeric: True
NaN count: 0

,number_inpatient,time_in_hospital,number_emergency,number_outpatient,num_medications,num_lab_procedures,diabetesMed,insulin,metformin,admission_type_id,discharge_disposition_id,max_glu_serum,A1Cresult,age,gender,readmitted,race_AfricanAmerican,race_Asian,race_Caucasian,race_Hispanic,race_Other,diag_1_Circulatory,diag_1_Diabetes,diag_1_Digestive,diag_1_Genitourinary,diag_1_Injury,diag_1_Musculoskeletal,diag_1_Neoplasms,diag_1_Other,diag_1_Respiratory,diag_2_Circulatory,diag_2_Diabetes,diag_2_Digestive,diag_2_Genitourinary,diag_2_Injury,diag_2_Musculoskeletal,diag_2_Neoplasms,diag_2_Other,diag_2_Respiratory
0,0,1,0,0,8,51,1,2,0,1,1,0,0,4,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
1,0,4,0,0,21,70,1,2,2,3,1,0,0,6,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
2,0,6,0,0,16,27,1,2,0,1,1,0,0,7,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,2,0,0,11,41,1,1,0,1,1,0,0,6,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
4,0,1,0,0,15,44,1,2,0,2,1,0,0,5,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0

In [110]:
# Print all feature columns and their dtypes for test set
print(f'  {"#":>3s}  {"Column":38s}  {"Dtype":8s}  {"Unique":>6s}  Encoding')
print(f'  {"---":>3s}  {"":-<38s}  {"":-<8s}  {"":-<6s}  --------')
for i, col in enumerate(df_test_selected.columns):
    dtype = str(df_test_selected[col].dtype)
    uniq = df_test_selected[col].nunique()
    if col in ['number_inpatient','time_in_hospital','number_emergency',
               'number_outpatient','num_medications','num_lab_procedures',
               'admission_type_id','discharge_disposition_id']:
        enc = 'Numerical'
    elif col in ['diabetesMed','gender']:
        enc = 'Binary'
    elif col in ['insulin','metformin','max_glu_serum','A1Cresult','age']:
        enc = 'Ordinal'
    elif col == 'readmitted':
        enc = 'Target (binary)'
    else:
        enc = 'One-Hot'
    print(f'  {i:3d}  {col:38s}  {dtype:8s}  {uniq:6d}  {enc}')
print(f'\n  Total: {df_test_selected.shape[1]} columns  |  {df_test_selected.shape[0]} rows')

# Print AGE (Ordinal) for test set
print('=== AGE (Ordinal) ===')
age_labels = {0:'[0-10)',1:'[10-20)',2:'[20-30)',3:'[30-40)',4:'[40-50)',5:'[50-60)',6:'[60-70)',7:'[70-80)',8:'[80-90)',9:'[90-100)'}
age_counts = df_test_selected['age'].value_counts().sort_index()
for val, count in age_counts.items():
    print(f"  {val}  ({age_labels.get(val, str(val))}): {count}")

# Print GENDER (Binary) for test set
print('=== GENDER (Binary) ===')
print('0 = Female  |  1 = Male')
print(df_test_selected['gender'].value_counts().sort_index())

# Print RACE (One-Hot) for test set
print('=== RACE (One-Hot) ===')
race_cols = [c for c in df_test_selected.columns if c.startswith('race_')]
for col in sorted(race_cols):
    print(f"  {col:25s}: {df_test_selected[col].sum()}")

    #  Column                                  Dtype     Unique  Encoding
  ---  --------------------------------------  --------  ------  --------
    0  number_inpatient                        int64         19  Numerical
    1  time_in_hospital                        int64         14  Numerical
    2  number_emergency                        int64         17  Numerical
    3  number_outpatient                       int64         28  Numerical
    4  num_medications                         int64         70  Numerical
    5  num_lab_procedures                      int64        108  Numerical
    6  diabetesMed                             int64          2  Binary
    7  insulin                                 int64          4  Ordinal
    8  metformin                               int64          4  Ordinal
    9  admission_type_id                       int64          8  Numerical
   10  discharge_disposition_id                int64         23  Numerical
   11  max_glu_serum                           int64          4  Ordinal
   12  A1Cresult                               int64          4  Ordinal
   13  age                                     int64         10  Ordinal
   14  gender                                  int64          2  Binary
   15  readmitted                              int64          2  Target (binary)
   16  race_AfricanAmerican                    int64          2  One-Hot
   17  race_Asian                              int64          2  One-Hot
   18  race_Caucasian                          int64          2  One-Hot
   19  race_Hispanic                           int64          2  One-Hot
   20  race_Other                              int64          2  One-Hot
   21  diag_1_Circulatory                      int64          2  One-Hot
   22  diag_1_Diabetes                         int64          2  One-Hot
   23  diag_1_Digestive                        int64          2  One-Hot
   24  diag_1_Genitourinary                    int64          2  One-Hot
   25  diag_1_Injury                           int64          2  One-Hot
   26  diag_1_Musculoskeletal                  int64          2  One-Hot
   27  diag_1_Neoplasms                        int64          2  One-Hot
   28  diag_1_Other                            int64          2  One-Hot
   29  diag_1_Respiratory                      int64          2  One-Hot
   30  diag_2_Circulatory                      int64          2  One-Hot
   31  diag_2_Diabetes                         int64          2  One-Hot
   32  diag_2_Digestive                        int64          2  One-Hot
   33  diag_2_Genitourinary                    int64          2  One-Hot
   34  diag_2_Injury                           int64          2  One-Hot
   35  diag_2_Musculoskeletal                  int64          2  One-Hot
   36  diag_2_Neoplasms                        int64          2  One-Hot
   37  diag_2_Other                            int64          2  One-Hot
   38  diag_2_Respiratory                      int64          2  One-Hot

  Total: 39 columns  |  20289 rows
=== AGE (Ordinal) ===
  0  ([0-10)): 28
  1  ([10-20)): 121
  2  ([20-30)): 327
  3  ([30-40)): 762
  4  ([40-50)): 1903
  5  ([50-60)): 3409
  6  ([60-70)): 4624
  7  ([70-80)): 5062
  8  ([80-90)): 3479
  9  ([90-100)): 574
=== GENDER (Binary) ===
0 = Female  |  1 = Male
gender
0    10828
1     9461
Name: count, dtype: int64
=== RACE (One-Hot) ===
  race_AfricanAmerican     : 3694
  race_Asian               : 115
  race_Caucasian           : 15326
  race_Hispanic            : 394
  race_Other               : 284

In [112]:
# Save clean train and test datasets to CSV files
# These files can be used directly for machine learning

df_selected.to_csv('clean_train_dataset.csv', index=False)
df_test_selected.to_csv('clean_test_dataset.csv', index=False)
print('Clean train and test datasets saved as CSV files.')

Clean train and test datasets saved as CSV files.

In [111]:
print(df_selected.columns.equals(df_test_selected.columns))

True